CREATE TYPE public.propertytype AS ENUM ('string', 'integer', 'date', 'image');


CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);


CREATE TABLE objecttypes (
    typeid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer,
    typename character varying NOT NULL,
    CONSTRAINT objecttypes_pkey PRIMARY KEY (typeid),
    CONSTRAINT objecttypes_userid_fkey FOREIGN KEY (userid) REFERENCES users ("Id") ON DELETE SET NULL
);


CREATE TABLE games (
    gameid integer GENERATED BY DEFAULT AS IDENTITY,
    gamecode character(7) NOT NULL,
    userid integer,
    objecttypeid integer,
    name character varying(50) NOT NULL,
    public boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT games_pkey PRIMARY KEY (gameid),
    CONSTRAINT games_objecttypeid_fkey FOREIGN KEY (objecttypeid) REFERENCES objecttypes (typeid) ON DELETE RESTRICT,
    CONSTRAINT games_userid_fkey FOREIGN KEY (userid) REFERENCES users ("Id") ON DELETE SET NULL
);


CREATE TABLE objects (
    objectid bigint GENERATED BY DEFAULT AS IDENTITY,
    typeid integer NOT NULL,
    objectname character varying NOT NULL,
    CONSTRAINT objects_pkey PRIMARY KEY (objectid),
    CONSTRAINT objects_typeid_fkey FOREIGN KEY (typeid) REFERENCES objecttypes (typeid) ON DELETE CASCADE
);


CREATE TABLE typeproperties (
    propertyid bigint GENERATED BY DEFAULT AS IDENTITY,
    typeid integer NOT NULL,
    propertyname character varying NOT NULL,
    propertytype propertytype NOT NULL,
    CONSTRAINT typeproperties_pkey PRIMARY KEY (propertyid),
    CONSTRAINT typeproperties_typeid_fkey FOREIGN KEY (typeid) REFERENCES objecttypes (typeid) ON DELETE CASCADE
);


CREATE TABLE objectproperties (
    objectid bigint NOT NULL,
    propertyid bigint NOT NULL,
    propertyvalue bytea NOT NULL,
    CONSTRAINT objectproperties_pkey PRIMARY KEY (objectid, propertyid),
    CONSTRAINT objectproperties_objectid_fkey FOREIGN KEY (objectid) REFERENCES objects (objectid) ON DELETE CASCADE,
    CONSTRAINT objectproperties_propertyid_fkey FOREIGN KEY (propertyid) REFERENCES typeproperties (propertyid) ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE UNIQUE INDEX games_gamecode_key ON games (gamecode);


CREATE INDEX "IX_games_objecttypeid" ON games (objecttypeid);


CREATE INDEX "IX_games_userid" ON games (userid);


CREATE INDEX "IX_objectproperties_propertyid" ON objectproperties (propertyid);


CREATE INDEX "IX_objects_typeid" ON objects (typeid);


CREATE INDEX "IX_objecttypes_userid" ON objecttypes (userid);


CREATE INDEX "IX_typeproperties_typeid" ON typeproperties (typeid);


CREATE INDEX "EmailIndex" ON users ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON users ("NormalizedUserName");


